### ISSUE TITLE
Server not running upon bringing up container?

### ISSUE THREAD

**Issue by anLizard** [arugifa/standardnotes-server-docker#1]
docker-compose.yml:
```
version: "3"

networks:
  sn:

services:

  standardnotes-server:
    image: arugifa/standardnotes-server
    container_name: standardnotes-server-0
    expose:
      - 3000
    networks:
      - sn
    depends_on:
      - mariadb-sn
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOST=mariadb-sn
      - DB_DATABASE=sn
      - DB_USERNAME=sn
      - DB_PASSWORD=secret1
    labels:
      - caddy.address=sn.$MY_DOMAIN/api
      - caddy.targetport=3000

  mariadb-sn:
    image: mariadb
    container_name: mariadb-standardnotes-0
#    command: >
#      sh -c 'while ! nc -vz mysql 3306 ; do sleep 10 ; done &&
#             bundle exec rails db:migrate &&
#             bundle exec rails server -b 0.0.0.0'
    networks:
      - sn
    restart: always
    volumes:
      - ./standardnotes/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=sn
      - MYSQL_USER=sn
      - MYSQL_PASSWORD=secret1
      - MYSQL_ROOT_PASSWORD=secret2
```

If I try to register on the server, I just get "A server error occurred while trying to register. Please try again."

Container logs only show this:
`standardnotes-server-0  | /data/src`

I tried it with the command part uncommented as well. Same result.
